name: dart_things
description: Drink more water, drink less beer to beat a bear.
version: 0.5.2
repository: https://github.com/innerwilds/dart_things

environment:
  sdk: ^3.5.4

dependencies:
  characters: ^1.3.0
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
