name: dart_things
description: Drink more water, drink less beer to beat a bear.
version: 0.0.6

environment:
  sdk: ^3.5.4

dependencies:
  characters: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
